server:
  port: 5174
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/operations
    username: root
    password: developer.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
